# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-04 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
